### PR TITLE
location details

### LINKED ISSUE #226: Announce location/venue
We're ready to announce the location and venue for this year's conference. That requires updating the header and adding a content section at the bottom of the page with information of the venue. We're **not** adding a section with information on the closing diner venue for now.

### TODO

- [ ] update header graphic
- [ ] add location text in header besides dates
- [ ] add content section for location/venue below _"Past Speakers"_ section with
  - [ ] title & text
  - [ ] venue photo
  - [ ] map

### Resources

* Desktop design: https://app.abstract.com/projects/61319c30-5f7e-11e9-97d1-abba5ef9115e/branches/a3af1a5b-3521-4888-986e-2e2746596644/commits/latest/files/e6b9cd4c-def8-41b2-8b8c-db26164ae2ee/layers/94E31730-3D18-43AC-93F9-1AA7B808A588?collectionId=d42ca52e-6bac-4be7-a4a4-62d6e223dc37&collectionLayerId=e5b09073-7cbe-4c9d-8a1e-4c962c0873bc
* Mobile design: https://app.abstract.com/projects/61319c30-5f7e-11e9-97d1-abba5ef9115e/branches/a3af1a5b-3521-4888-986e-2e2746596644/commits/3307f1533c4b64b1492c8df7a2e43e14f3746a3a/files/e6b9cd4c-def8-41b2-8b8c-db26164ae2ee/layers/BF4B7744-1981-4B11-94FB-02F63B8F616F ( @marhigh this file seems empty? can you clarify?)
* Text & photo for venue: https://3.basecamp.com/4551353/buckets/17581315/todos/3838606747

### PR DESCRIPTION
**Pull request by mandurisaimounika**
Bildschirmfoto 2021-06-11 um 09 20 53

closes #226

### CODE REVIEW

**Comment by mandurisaimounika** [comment]
@marcoow this is the new branch created from master and updated codes.

**Review by marcoow — CHANGES_REQUESTED** [review]
This is a good start but not quite there tbh.

* can we use our regular text style for the text? This seems to be larger and bolder than other text elsewhere on the page:

Bildschirmfoto 2021-06-10 um 18 08 07

* the mobile view renders the link in white on white background:

  Bildschirmfoto 2021-06-10 um 18 09 07

* the mobile view is also lacking padding to the left and right as well as at the bottom towards the next section
* finally, we should show the image and map in the mobile view as well?

Can you also use this image instead of the fountain?

Meeting_GalaRoom_PB_(1)

**Comment by mandurisaimounika** [comment]
> This is a good start but not quite there tbh.
> 
> * can we use our regular text style for the text? This seems to be larger and bolder than other text elsewhere on the page:
> 
> Bildschirmfoto 2021-06-10 um 18 08 07
> 
> * the mobile view renders the link in white on white background:
>   Bildschirmfoto 2021-06-10 um 18 09 07
> * the mobile view is also lacking padding to the left and right as well as at the bottom towards the next section
> * finally, we should show the image and map in the mobile view as well?
> 
> Can you also use this image instead of the fountain?
> 
> Meeting_GalaRoom_PB_(1)

@marcoow I have added the changes and updated the mobile view.

**Comment by marcoow** [comment]
I fixed this so we can launch

**Review by marcoow — APPROVED** [review]

**Pull request merged**
