### PR TITLE
2019 conference

### LINKED ISSUE #142: Update Website for 2019 Conference
The Emberfest page must be updated to promote the upcoming October 2019 conference.
I have attached the files needed for the header update and will upload the footer mascot as well.

SVG for the header:
https://drive.google.com/open?id=1FgwfGga56slCQiv5uJdnUtDGFxzoeZ1F
PNG:
https://drive.google.com/open?id=1C7pOgutP_X6Nd3NSUwJrmHQceCbh2ShJ
MASCOT:
https://drive.google.com/open?id=1J9vekIEDo-V-R32JjP-cW3P6F6epuNHq

### PR DESCRIPTION
**Pull request by wadie**
closes #142

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@wadie is this staged somewhere?

**Comment by wadie** [comment]
I don't think so, I just clone it and run `bundle exec jekyll serve`

**Comment by marcoow** [comment]
@wadie, @ghislaineguerin: if you push anything, this should get deployed via Netlify

**Comment by marcoow** [comment]
@wadie, @ghislaineguerin: can we get this out tomorrow? I think these things are still missing:

- [ ] replace speakers with _Past Speakers_ and show Tom Dale, Jessica Jordan, Melanie Sumner, Chad Hietala, Lauren Tan, Ricardo Mendes; remove the _"We have a great lineup…"_ paragraph
- [ ] replace sponsors section with _"Past Sponsors"_, showing **all** of the sponsor logos of all sponsors we ever had in small size (like under "Supporting Sponsors")
- [ ] maybe we should change some of the colors to match the header image better (@ghislaineguerin, what do you think)?
- [ ] replace the venue photo with a map of Europe maybe? @ghislaineguerin, what do you think?

**Comment by ghislaineguerin** [comment]
@wadie please change these colors to match the image:
image
image

**Comment by ghislaineguerin** [comment]
@wadie color and map changes make sense to me. I will create the map image and post here.
FYI @marcoow

**Comment by ghislaineguerin** [comment]
europe-map

**Comment by ghislaineguerin** [comment]
europe-map
@wadie please use this map image

**Comment by ghislaineguerin** [comment]
europe-map

**Comment by ghislaineguerin** [comment]
image
@wadie can we make all the circles the same height ?

**Comment by marcoow** [comment]
thanks 🙌

**Comment by ghislaineguerin** [comment]
mascot
@wadie please replace the mascot with this image. thanks
@marcoow FYI

**Pull request merged**
