### PR TITLE
kloeckner-i logo

### LINKED ISSUE #115: Add kloeckner.i as premier sponsor
logo: 
[kloeckner-i.svg.zip](https://github.com/emberfest/emberfest.github.io/files/2136947/kloeckner-i.svg.zip)

### PR DESCRIPTION
**Pull request by wadie**
closes #115

### CODE REVIEW

**Comment by wadie** [comment]
oh forgot about it..fixed!

**Comment by wadie** [comment]
Which ? :thinking:

**Comment by marcoow** [comment]
Ah sorry, this removes the PNG of course. That doesn't work though as it's still used on the 2017 site (https://emberfest.eu/2017/).

**Comment by wadie** [comment]
But that PNG still exists in the 2017 directory..I removed it from the main images directory since we don't use it right now anymore

**Comment by marcoow** [comment]
ah I see - makes sense 👍

**Pull request merged**
