### PR TITLE
Venue

### PR DESCRIPTION
**Pull request by marcoow**
Bildschirmfoto 2023-06-21 um 12 27 22

### CODE REVIEW

**Review by balinterdi — APPROVED** [review]
LGTM!

**Comment by davidhajba** [comment]
All the assets are [HERE](https://shared-assets.adobe.com/link/1a48c974-c6cc-4c69-5572-4f68c4ea2aaa) 

* background pattern of 'Past Speakers' should be updated to 'pattern_outline-orange' (in assets)
* pls update the buttons for consistent height 74px Hovers are [HERE](https://www.sketch.com/s/150ed20a-d7c3-46a1-8151-89fba683acae/v/a5b8Oz/p/BE993FE2-E578-440C-A931-8457C6430A8A/canvas?posX=-138.6155257832886&posY=-468.8455685138896&zoom=0.6950476169586182) 
* on desktop venue pic should have a max width/height 540px - therefore the whole section is not that tall
* The 'This year’s EmberFest will take place in Próxima Estación' text box should have a 540px max width
* The 'CHECK ON MAP' button should be left aligned with the text box above
* The background blur value of the 'Past Sponsors' / 'Organizers' logo container boxes should be updated
* The shadow of the 'Past Sponsors'section should be aligned with Sketch
* The portraits should be updated (new ones in assets)
* I would recommend updating the 'Ember {{fest}} 2022' video thumbnail - just uploading in Sketch

**Comment by marcoow** [comment]
> background pattern of 'Past Speakers' should be updated to 'pattern_outline-orange' (in assets)

changed

> pls update the buttons for consistent height 74px Hovers are [HERE](https://www.sketch.com/s/150ed20a-d7c3-46a1-
8151-89fba683acae/v/a5b8Oz/p/BE993FE2-E578-440C-A931-8457C6430A8A/canvas?posX=-138.6155257832886&posY=-468.8455685138896&zoom=0.6950476169586182)

> changed

> on desktop venue pic should have a max width/height 540px - therefore the whole section is not that tall

changed but with max-width 440px – otherwise doesn't work on all resolutions

> The 'This year’s EmberFest will take place in Próxima Estación' text box should have a 540px max width

changed

> The 'CHECK ON MAP' button should be left aligned with the text box above

changed

> The background blur value of the 'Past Sponsors' / 'Organizers' logo container boxes should be updated

unrelated – can change later if necessary

> The shadow of the 'Past Sponsors'section should be aligned with Sketch

changed

> The portraits should be updated (new ones in assets)

unrelated – can change later if necessary

> I would recommend updating the 'Ember {{fest}} 2022' video thumbnail - just uploading in Sketch

unrelated – can change later if necessary

**Comment by davidhajba** [comment]
Thank you for the updates

* the 'GET INVOLVED!' and the 'SUBSCRIBE' buttons are not changed yet to 74px height on my Sarafi

* in design details are important (video thumbnail, profile pictures, venue picture size, background blur)
Imo - these are responsible for ~ 30% of the UX
I understand it is not high prio, but would be good to not forget and update when there's capacity

**Comment by davidhajba** [comment]
* 'Past Sponsors' H1 should be 150px distance from the top of the background box, currently is too far

**Comment by marcoow** [comment]
@davidhajba we can't get lost in the details here – I understand details are important but at this point effort and value aren't in a reasonable relation. Please create a follow-up ticket with everything that needs to be done from your perspective and we'll do it later.

@balinterdi please merge whenever you're ready to announce.

**Review by davidhajba — APPROVED** [review]

**Pull request merged**
