### PR TITLE
Add talk titles to schedule table

### PR DESCRIPTION
**Pull request by balinterdi**
See #57. I realize we don't have the titles for about half of the talks but I think it's still worth to merge this so that we share the info that we ourselves have.

### CODE REVIEW

**Comment by marcoow** [comment]
@balinterdi: I guess this also need some CSS fixes: 
bildschirmfoto 2017-09-15 um 14 32 40

**Comment by balinterdi** [comment]
@marcoow Which ones? To me, it's mostly that the Lunch and Snack break could be vertically centered. Is there anything more?

**Comment by marcoow** [comment]
Just looks a bit weird with the wrapping times I think.

**Comment by balinterdi** [comment]
@marcoow Indeed, I've submitted [this PR](https://github.com/emberfest/emberfest.github.io/pull/60) to fix it. Could you review/merge?

**Pull request merged**
