### PR TITLE
2019 program

### PR DESCRIPTION
**Pull request by marcoow**
### TODO

- [x] fix order
- add missing photos:
  - [ ] Chad Carbert
  - [ ] Chris Ng
  - [x] Jon Kilroy

### CODE REVIEW

**Comment by marcoow** [comment]
@alexspeller, @jkintscher this is only missing 3 photos and the actual order we want - see list above

**Comment by alexspeller** [comment]
@marcoow photos updated on #178 now

**Comment by jkintscher** [comment]
Running order, as posted to Slack for final confirmation, is up here: https://gist.github.com/jkintscher/a53374cbf054ccd8df90f899b27b2524

**Comment by balinterdi** [comment]
Great!

There's a typo in Sergio's name: his family name is [Arbeo](https://twitter.com/Serabe), not Abero. I can fix this when I get a chance but noting it down if someone wants to merge before that.

**Comment by marcoow** [comment]
addressed the findings

**Pull request merged**
