### PR TITLE
Update Simplabs to Mainmatter

### LINKED ISSUE #373: Update simplabs to Mainmatter
logos: logos: https://drive.google.com/drive/folders/17WwGrrDHXFw5jHijGQ4Oy8TZXhU8nLpE?usp=sharing

domain: mainmatter.com

### PR DESCRIPTION
**Pull request by inesilva**
it closes #373

### CODE REVIEW

**Review by marcoow — CHANGES_REQUESTED** [review]
Please make sure to change this as well:

Bildschirmfoto 2022-09-16 um 12 47 30

**Comment by oscard0m** [comment]
Sorry, there was a miscommunication and seems we did the work twice. 🤦🏽 
https://github.com/emberfest/emberfest.github.io/pull/376

**Comment by inesilva** [comment]
> Sorry, there was a miscommunication and seems we did the work twice. 🤦🏽 #376
> 
> I think my PR is applying almost the same changes as you are doing here but:
> 
> * It uses a round logo for the Organizers section
> * It corrects Chris description with ~simplabs~ `Mainmatter`
> 
> @inesilva Would you be happy if we close this PR and we review that one instead?

Yes, we can do that

**Comment by oscard0m** [comment]
> Yes, we can do that

Thank you, and sorry for the misunderstanding and double work 🙏🏽

**Pull request closed without merging**
