### PR TITLE
Venue announcement

### PR DESCRIPTION
**Pull request by wadie**
Announcing this year's location and venue.

### CODE REVIEW

**Comment by wadie** [comment]
That's the font that @pichfl suggested and used the same colors as the title.

**Comment by marcoow** [comment]
I fixed it - it was horizontally condensed or whatever that's called ;)

**Comment by marcoow** [comment]
Please don't merge just yet

**Comment by marcoow** [comment]
argh, I just realized it doesn't blend with the background anymore now 🤦‍♂️

**Comment by marcoow** [comment]
@wadie 

> Please don't merge just yet

🙏

**Pull request merged**
