### PR TITLE
Temporary before 2024 version

### LINKED ISSUE #441: Prepare page for time between 2023 event and 2024 announcement
We need to update the site for the time between the 2023 event and the 2024 announcement. That means:

* preserving the current state of the page in `/2023` and adding a link to that in the footer (on the landing page and for all pages of all the past years)
* updating the landing page by
  * making the design a bit more generic (I guess that mainly means removing the bull)
  * removing the event dates and location at the top
  * removing the book-your-ticket button
  * removing the _"Ember {{fest}} 2022"_ section (video and text below)
  * changing _"Speakers"_ to _"Past Speakers"_
  * removing the schedule
  * removing the _"Conference Venue"_ section
  * changing the _"Sponsors"_ section to _"Past Sponsors"_ and making it include **all** sponsors from past years, all at the same level with the same size
* remove _"Cancellation"_, _"Sponsorships"_ from the footer of the landing page

Overall, this is kind of the same as mainmatter/eurorust.eu#201

### PR DESCRIPTION
**Pull request by yaigrie**
closes #441

### CODE REVIEW

**Review by marcoow — COMMENTED** [review]
Nice 🙌 

Only recognized 1 thing: the imprint and cancellation pages linked from the neutral landing page still have the 2023 header – can you make that header generic as well?

**Comment by jkintscher** [comment]
Yup, besides those headings the rest looks good to me as well 👍  Can take another look and approve once those are updated if nobody beats me to it.

**Comment by yaigrie** [comment]
@marcoow @jkintscher thank you, I updated the sidepage header :)

**Review by marcoow — COMMENTED** [review]
@yaigrie I just saw the 2023 page's foot and header of the subpages changed as well: https://deploy-preview-442--silly-leavitt-2e0668.netlify.app/2023/

**Pull request merged**
