### PR TITLE
Enhance get tickets button design

### LINKED ISSUE #324: Increase contrast of "buy tickets" button to background and de-emphasize social media buttons
Somebody pointed this out on Discord and I think he's right:

Screenshot 2022-08-30 at 20 14 48

The "Get your ticket" button blends in while the Twitter and mailing list buttons are quite big and draw a lot of attention further down the page.

### PR DESCRIPTION
**Pull request by inesilva**
It closes #324 
I increased the padding-bottom of the hero image, so that the text stays more on top of the Eiffel Tower.
I also added a shadow behind the button so it stands out more.

### CODE REVIEW

**Review by oscard0m — CHANGES_REQUESTED** [review]
👍🏽 to increasing the size of the button
👍🏽 adding a shadow to give more importance to the button

I still see some opportunities to improve the importance of this button a little bit:

### Improve the contrast ratio
The contrast ratio can reach better numbers. I found an interesting website where we can play with the colours of the background and the button to achieve a better contrast score:
https://buttonbuddy.dev/#generator

The values I introduced:
```css
--surface: #8a83c7;
--background: #2a3b90;
--color: #f9ead4;
```

image

### Social Buttons still are bigger
When checking the page, the Social Buttons still are bigger. Some ideas we can experiment with are:
- 💁🏽💡 Increase the `font-size` for the `GET YOUR TICKET` button
- 💁🏽💡 Increase the area (`padding`) for the `GET YOUR TICKET` button
- 💁🏽💡 Decrease the area (`padding`) for the `Twitter` and `Mailing List` buttons.
- 💁🏽💡 Make the icons appear in the same line with the text to make the button smaller.

**Comment by oscard0m** [comment]
Actually, we can merge what you did and we (I can do it) can do another iteration in a different PR.

**Review by oscard0m — APPROVED** [review]

**Comment by inesilva** [comment]
> Actually, we can merge what you did and we (I can do it) can do another iteration in a different PR.

Seems good to me, I will merge it and I can take a look again on this tomorrow

**Comment by balinterdi** [comment]
Thank you, that's an improvement, the box shadow really lifts it out. It still blends in with the Eiffel Tower behind it – if could dim the background somehow, I think that would solve it but there might be other ways to achieve the same.

**Comment by oscard0m** [comment]
> Thank you, that's an improvement, the box shadow really lifts it out. It still blends in with the Eiffel Tower behind it – if could dim the background somehow, I think that would solve it but there might be other ways to achieve the same.

I created a new issue where we can keep iterating the button: https://github.com/emberfest/emberfest.github.io/issues/363

**Pull request merged**
