### PR TITLE
2022

### PR DESCRIPTION
**Pull request by marcoow**
This gets the site ready for 2022. The location remains hidden for now, there's no schedule and no venue details etc. but this should be good for announcing.

**The tickets button won't show up correctly until we configure and switch on the event on ti.to!**

### CODE REVIEW

**Comment by balinterdi** [comment]
This year's site looks good but a lot of images seem to be broken for 2021:

Screenshot by Dropbox Capture

**Comment by marcoow** [comment]
fixed

**Comment by balinterdi** [comment]
@marcoow Now there is this:

Screenshot 2022-06-02 at 10 51 58

Sorry 😬

**Comment by marcoow** [comment]
I can't reproduce

**Comment by balinterdi** [comment]
@marcoow Nevermind, I can't reproduce it even in the same browser. Sorry for holding this up.

**Review by balinterdi — APPROVED** [review]

**Pull request merged**
