### PR TITLE
Add recap video of EmberFest 2021

### PR DESCRIPTION
**Pull request by inesilva**
It adds a section to watch the video of EmberFest 2021

### CODE REVIEW

**Comment by marcoow** [comment]
the embed doesn't seem to work?

Bildschirmfoto 2022-07-25 um 16 18 19

**Comment by oscard0m** [comment]
> the embed doesn't seem to work?
> 
> Bildschirmfoto 2022-07-25 um 16 18 19

To make it work you need to apply the proper YouTube embedded code:

`Go to the video -> Share -> Embeded`

Context here: https://stackoverflow.com/a/69169484/3237248

**Review by oscard0m — CHANGES_REQUESTED** [review]
Check my comment about adding `/embed` YouTube videos.

**Comment by inesilva** [comment]
> To make it work you need to apply the proper YouTube embedded code:
> 
> `Go to the video -> Share -> Embeded`
> 
> Context here: https://stackoverflow.com/a/69169484/3237248

Thanks! 
Should be working now :)

**Comment by marcoow** [comment]
Would it look better with the same style that we're using for "Past speakers" with the same background color, the croissants etc.? If we want to go with the blue background, we'd need to remove the bar between the blue background and the image above:

Bildschirmfoto 2022-07-25 um 17 28 32

Also the text flows very wide – we should use a maximum width for the paragraph, check the paragraph below in the past speakers section for reference.

**Comment by inesilva** [comment]
> Would it look better with the same style that we're using for "Past speakers" with the same background color, the croissants etc.? If we want to go with the blue background, we'd need to remove the bar between the blue background and the image above:
> 
> Bildschirmfoto 2022-07-25 um 17 28 32
> 
> Also the text flows very wide – we should use a maximum width for the paragraph, check the paragraph below in the past speakers section for reference.

I also like with the styling of the croissants divider.
The blue background is nice too but I don't know if it would be that easy to remove that line anyway, the image above doesn't have a straight line causing this space.

Right now, there is a rule in the sections to always apply a padding-bottom of 128px, I'm wondering if it wouldn't make sense to make this space smaller in smaller screens, it is a lot of space for padding that could be used to show more info?

**Review by oscard0m — APPROVED** [review]

**Pull request merged**
