### PR TITLE
add new artwork and improve design

### LINKED ISSUE #78: Replace background and bear with new artwork
[Archiv.zip](https://github.com/emberfest/emberfest.github.io/files/1695357/Archiv.zip)

`background.svg` replaces the Berlin skyline at the top, `icon.svg` replaces the bear at the bottom.

The dates in the artwork are correct. **Be sure to not mention what the artwork stands for as that is still secret!**

### PR DESCRIPTION
**Pull request by trabaldini**
closes #78

### CODE REVIEW

**Comment by trabaldini** [comment]
changed the skyline.svg text, should look like on the sticker. I didn't change the colors, this was the background image from the zip you uploaded. Shall I change it?
Also shall we keep the logo of Emberfest on top?

**Comment by marcoow** [comment]
Hm, but the background color on the website is `#bdccd4` and in the new design it seems to be `#f2f2f1`. We should use the latter one on the website as well (and replace the grey background further down with it as well).

And now - the logo at the top should not stay but be removed as it's now part of the logo.

**Comment by trabaldini** [comment]
The background of the artwork on my localhost looks like `#bdccd4`.
If I change the background color to `#f2f2f1`it looks like this:
screen shot 2018-02-15 at 11 12 34

**Comment by marcoow** [comment]
I think the SVG in #78 has a transparent background actually.

**Comment by trabaldini** [comment]
Yeah, the background-color was set somewhere else.
Changed the colors, but the problem now is when you're on the CoC, cancellation or imprint page there is no link back to the homepage. What can I use? Tried to make a link in the svg but that didn't work out...

**Comment by marcoow** [comment]
Can you just link the complete SVG on the other pages and make the header smaller (as in, use a different layout on the other pages with the same header image but far smaller?)

**Comment by trabaldini** [comment]
Smaller like this or more?

**Comment by marcoow** [comment]
I'd make it much smaller, more like a bar at the top

**Comment by trabaldini** [comment]
Made it smaller. If it has to be much smaller I should use another image maybe, because it's getting too small to read.

**Comment by marcoow** [comment]
Yes, using only the „Ember{{fest}}“ sounds good. Should be possible to extract only that out of the SVG.

**Comment by trabaldini** [comment]
Used the new logo for the sites, looks better!

**Comment by trabaldini** [comment]
Not sure if best solution, but looks better.

**Pull request merged**
