### PR TITLE
feat(mainmatter): replace 'simplabs' with 'Mainmatter'

### LINKED ISSUE #373: Update simplabs to Mainmatter
logos: logos: https://drive.google.com/drive/folders/17WwGrrDHXFw5jHijGQ4Oy8TZXhU8nLpE?usp=sharing

domain: mainmatter.com

### PR DESCRIPTION
**Pull request by oscard0m**
Fixes #373 

## TODO

- [x] update Twitter URL

### CODE REVIEW

**Comment by oscard0m** [comment]
screenshot

I've reproduced the round logo with CSS. Should we have it available as SVG/PNG in our Mainmatter logo folder?

<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 105.0.0.0 on Mac OS 10.15.7
Viewport:  1920 x 944 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-376--silly-leavitt-2e0668.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=105.0&resolution=1920x944&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-376--silly-leavitt-2e0668.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=63245ac40ae4e4000857c06e&commentID=63245b87508f1f23d0207022&resolution=resolved)

**Comment by marcoow** [comment]
@oscard0m the round symbol is in Google Drive already

**Comment by oscard0m** [comment]
> @oscard0m the round symbol is in Google Drive already

Can you link it @marcoow? I don't find it.

**Comment by marcoow** [comment]
https://drive.google.com/drive/folders/1ozJ0VDxt1NcQM-OoqL753kyZkqzNJYhP?usp=sharing

**Comment by oscard0m** [comment]
> https://drive.google.com/drive/folders/1ozJ0VDxt1NcQM-OoqL753kyZkqzNJYhP?usp=sharing

I don't see the round versions. Maybe they are not shared with my Google user?

**Comment by inesilva** [comment]
> > https://drive.google.com/drive/folders/1ozJ0VDxt1NcQM-OoqL753kyZkqzNJYhP?usp=sharing
> 
> I don't see the round versions. Maybe they are not shared with my Google user? This is what I see for the white symbol:
> 
> image

I also didn't find it

I'm approving, the changes look good to me

**Review by inesilva — APPROVED** [review]

**Review by marcoow — APPROVED** [review]

**Pull request merged**
