### PR TITLE
add location + decoration

### PR DESCRIPTION
**Pull request by yaigrie**

### CODE REVIEW

**Review by marcoow — APPROVED** [review]
nice 🙌

**Comment by marcoow** [comment]
⚠️ please don't merge yet

**Comment by balinterdi** [comment]
Okay, but why?

**Comment by marcoow** [comment]
…because we want to orchestrate this with updating the social media accounts, sending out an email, tweets etc.

**Comment by marcoow** [comment]
social media assets:

avatar
background-twitter
background

**Pull request merged**
